### ISSUE TITLE
Configuring URL lists in policies prevent users from storing custom values

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#252]
We have configured for example the policy PopupsAllowedForUrls to allow pop-ups for some well-known web sites on all clients. If a user now adds additional domains to the allow list, the policy overwrites their custom settings. 
With this, we cannot enforce a URL list and simultaneously allow the user to add custom URLs. We see this issue also in other policies.

**Comment by Y-Kelly** [comment]
@joegoerlich Based upon the documentation (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#popupsallowedforurls) it is my understanding that this behavior is by design.  

A user's personal configuration is only used if the policy is not configured.  

![image](https://user-images.githubusercontent.com/74324031/140231403-1c2fe8fa-911c-4df8-bfcf-de5375604717.png)

Thanks! 

_-Kelly_

**Comment by joegoerlich** [comment]
Hi @Y-Kelly, the issue is not that the feature doesn't work as expected. It is more that we miss a feature to enforce an allowlist and still give the user an option to have their own allowlist additionally.
Maybe this is a feature request if the present implementation is as it was intended to be?!

**Comment by Y-Kelly** [comment]
@joegoerlich You are correct that PopupsAllowedForUrls cannot be set at Recommended.  I took a quick look and do not see any active work item for this change.  

Feel free to submit a feature request through the browser. ("..." menu > Help and feedback > Send feedback).  Thanks!
