### ISSUE TITLE
How to Reset Edge cloud-sync article not clear

### ISSUE THREAD

**Issue by cmo-gp** [MicrosoftDocs/Edge-Enterprise#281]
[Enter feedback here]
Collections are not syncing across different devices running dev-edge (they never have), but this 'How to reset sync' article is not clear. I have a set of collections, and also a set of open tabs on one device that I want to be the new master collections that will sync with all other devices. But I have no idea how to do this. It's also not clear if collections, or which collection (or open tabs) will be deleted when I do a reset.

Also it says I have to sign-out of all devices - but that is impossible as the devices are at different locations (isn't that the point of the sync feature, to sync multiple devices at different locations?).  I can't be in two physical places at the same time.

As a personal comment, it's my opinion that the Sync feature (specifically collections, and synced tabs) is a really cool idea and feature, but it's my experience this is the most unreliable aspect of using Edge. I have never, despite trying for months, got this feature to work. It seems that asking users to do the impossible (sign out of all devices that are hundreds of miles apart) in order to fix an MS bug (sync not working) is a less than satisfactory solution to the problem.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data](https://docs.microsoft.com/en-gb/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@cmo-gp Hello!  Sorry to hear about the issues you've been having!  You mentioned Collections are not syncing, are other things like passwords, history, etc. syncing as expected?  

The "Reset Microsoft Edge data in the cloud" article does mention to sign out of Microsoft Edge on all devices except the one you are performing the reset on because that browsing data on the specific device will not be deleted.  

See message explaining from edge://settings/profiles/sync after selecting "Reset Sync"

![image](https://user-images.githubusercontent.com/74324031/147980325-fbfa605b-cb99-4aef-beeb-8f9ec5b72342.png)

Unfortunately, if your devices are far apart like you mentioned it can make resetting difficult but hopefully it is not something that would need to be done very often.  

I also wanted to suggest reaching out to Support if issues persist.   https://microsoftedgesupport.microsoft.com/hc/en-us  Especially for Sync issues, it can be a case-by-case basis and Support should be able to gather logs and help investigate your specific issue.  

Thanks!

**Comment by Y-Kelly** [comment]
Clean up of old issues.  If issues are continuously reproducing, recommend reaching out to Support like mentioned.
