### ISSUE TITLE
Out-of-date UI

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/Edge-Enterprise#33]
The AT configuration profile UI does not appear like that anymore; there is not separate production selection between Windows, Office, and Edge.

It now looks like the Group Policy UI with Computer Configuration and User Configuration nodes with all Windows, Office, and Edge sub-nodes meshed within.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47a3485-ce79-9bbf-aac2-060792af6d06
* Version Independent ID: 9e9eacea-96fd-6856-da7e-7149edefabe4
* Content: [Configure Microsoft Edge policy settings for Windows using Microsoft Intune](https://docs.microsoft.com/en-us/deployedge/configure-edge-with-intune)
* Content Source: [edgeenterprise/configure-edge-with-intune.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/configure-edge-with-intune.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
Clean up of old issues.  The specific document has been updated a few times since this issue was opened.  If the issue still reproduces please open a new issue and include relevant information/repro steps in the Comment section (Also, it would be helpful to have a screenshot specifically of the outdated UI). Thanks!
