### ISSUE TITLE
Group Policy for "Enable global window list in Internet Explorer Mode" refers to this page but there is no info on the feature

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftDocs/Edge-Enterprise#344]
Hi,

Am trying to understand how "Enable global window list in Internet Explorer Mode" works, and Group Policy Editor refers to this page, but there isn't any info available.  Can this page be updated please?

![image](https://user-images.githubusercontent.com/15855352/169359189-aeb1a12d-f96c-476b-a5fe-86520cbacd8d.png)

Kind Regards,

Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418ea780-28cd-c78d-8855-df5188dd4be9
* Version Independent ID: 15be2361-06cf-5683-9213-8aec3aebef67
* Content: [What is Internet Explorer mode?](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@loaderladdy I've reached out to the team and this refers to the global shell window list (CLSID_ShellWindows, SHDocVw.ShellWindows). Standalone IE tabs (as well as WebOCs and explorer.exe folder windows) register with the global window list; IE mode, CLSID_InternetExplorerManager, and a few other IE scenarios use a per-session window list to isolate their tabs.

If you enable this policy, IE mode tabs register with the global window list instead of the per-session window list. Note that applications which use the global window list may find that IE mode tabs behave differently in various ways compared to regular IE tabs if they try to automate them, which may break the callers. The shell window list is also used internally in IE for features like frame targeting, so enabling the use of the global window list may create unexpected cross-talk between IE mode and other IE sessions/windows.

Can you share if you are trying to solve a specific scenario by using this policy?  Thanks!

**Comment by loaderladdy** [comment]
@Y-Kelly  hi, yeah, some of our devs had been working with Fast Track App Assure engineers who recommended enabling this control so I was after more info before I had it enabled. Our devs write VBA apps that were scraping data out of IE11 apps window to write back back to a pre-populated form sending letters to customers. The apps will be using IE Mode once IE11 is retired. I appreciate this control only works when the disable IE as a stand-alone browser is set too.  I’m interested to know more about the potential implications of this particular setting. Is there a recommendation to only enable it on a case by case basic, or globally across the user base, and are there incident triage implications if the setting is enabled vs not enabled? 

Many thanks

**Comment by Y-Kelly** [comment]
@loaderladdy Great to hear that your devs are already working with FastTrack AppAssure, that is the best course of action and they should be able to help with the questions.
