### ISSUE TITLE
ADMX policy "Control which extensions are installed silently" Reapplies every sync

### ISSUE THREAD

**Issue by Temilit** [MicrosoftDocs/Edge-Enterprise#373]
ADMX policy "Control which extensions are installed silently" Reapplies every sync which causes the extensions listed in policy to be removed and then reinstalled, this causes aditional popups since many extensions opens a new tab upon installation.

Observed version the seems to be affected.
Public: 103.1264.37 (64bit) version.
Canary: 105.1304.0 (64bit) version.

Edit: add:
After rollback to version 102.0.1245.30 the problem no longer exists, so it seems the problem occured somewhere between these versions

**Comment by Y-Kelly** [comment]
@Temilit Hello - This issue was inherited upstream from Chromium, we are expecting a fix to be included in the next Stable channel release.  For additional information, please see this discussion in the MS Edge Enterprise Tech Community: https://techcommunity.microsoft.com/t5/enterprise/quot-some-extensions-are-not-allowed-quot-after-last-update/m-p/3560964/highlight/true#M4693
