### ISSUE TITLE
Description of IE mode prerequisites

### ISSUE THREAD

**Issue by hhidakaa** [MicrosoftDocs/Edge-Enterprise#374]
The following page lists the prerequisites for IE mode, but they are listed by update number (KB~).
I would like to see the build number corresponding to the update so that I can check if the prerequisites are met by the build number of the device, instead of KB~.
Thank you.

https://docs.microsoft.com/en-us/deployedge/edge-ie-mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418ea780-28cd-c78d-8855-df5188dd4be9
* Version Independent ID: 15be2361-06cf-5683-9213-8aec3aebef67
* Content: [What is Internet Explorer mode?](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Y-Kelly** [comment]
@hhidakaa Thanks for reaching out.  KBs are utilized in the documentation because the underlying Windows and IE builds need to be updated for IE mode to work properly.  KBs can also apply to more than one OS/build number.  

Also, listing the KBs as prerequisites provides a consistent form of documentation for this team and MS.  You can easily check for the KBs by looking at the update history in your device settings.
