### ISSUE TITLE
Cannot find ADMX files

### ISSUE THREAD

**Issue by phillipge** [MicrosoftDocs/Edge-Enterprise#392]
[Enter feedback here]

Are you sure this is still accurate?  I went to https://www.microsoft.com/en-us/edge/business/download looking for MicrosoftEdgePolicyTemplates.cab and not a single link worked on the site.  I tried with multiple browsers as well.  Is there any other source for the ADMX files?  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4fa0af-82d8-c1ca-02b3-fc55eb620ff3
* Version Independent ID: bd546e78-3406-0fdd-2aea-d0bd72be9f38
* Content: [Configure Microsoft Edge for Windows with policy settings](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@phillipge Hello - I just tested (highlight links below) and was able to download the policy files after accepting the agreement.

![image](https://user-images.githubusercontent.com/74324031/182197363-f10596a2-3ef1-444e-a42f-29bf6f5e62fa.png)

![image](https://user-images.githubusercontent.com/74324031/182197753-6fc17558-dc0a-4c0d-88b1-f239076e6ee2.png)

Can you try to see if your issue is still reproducing?

**Comment by Y-Kelly** [comment]
We've had some other reports of the issue and received confirmation that it has been resolved.  Closing.  

If you have general questions regarding Microsoft Edge please reach out on the [Microsoft Edge Tech Community](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsiderForum) or for Enterprise specific questions please visit the [Enterprise section of the Tech Community](https://techcommunity.microsoft.com/t5/enterprise/bd-p/EdgeInsiderEnterprise). Thanks!
