### ISSUE TITLE
Proactive Authentication is deprecated since v90

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/Edge-Enterprise#396]
The policy for Proactive Authentication is deprecated since v90. This page still refers to that one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1de76e25-d6fb-af1a-f593-f9695e4da22c
* Version Independent ID: 3bb59466-8415-287d-d6f8-bbe32a6b112e
* Content: [Microsoft Edge identity support and configuration](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-identity#automatic-sign-in)
* Content Source: [edgeenterprise/microsoft-edge-security-identity.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-security-identity.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **v-danwesley**

**Comment by Y-Kelly** [comment]
@joegoerlich We've confirmed with our developers that the Proactive Authentication service is not deprecated.  It is just the policy  "ProactiveAuthEnabled" that has been obsolete since v90 because Proactive Authentication has been integrated as a part of sign in.

To configure browser sign in, you can use the [BrowserSignin](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#browsersignin) policy.

We are working to update and improve the documentation.  Thanks for the feedback.
