### ISSUE TITLE
Enterprise New Tab Page news content not respecting Microsoft 365 admin center setting

### ISSUE THREAD

**Issue by SmithingJon** [MicrosoftDocs/Edge-Enterprise#472]
The latest version of Microsoft edge shows the default Microsoft news new tab page even when the Microsoft news setting in the 365 Admin center is set to "Microsoft 365 Content only."

Issue happens on both Intune-managed, and unmanaged browsers.

Clicking the "Microsoft 365" header once changes the tab to the Microsoft 365 content, and only that content will show on subsequent new tabs.

In the Winadmins discord I was able to report the issue to an Edge developer, but I have had no public acknowledgement of that issue or any fix.

**Comment by SmithingJon** [comment]
![image](https://user-images.githubusercontent.com/81338645/215547745-b760b39d-3b44-4330-be34-58c8be874055.png)

**Comment by SmithingJon** [comment]
![image](https://user-images.githubusercontent.com/81338645/215548161-fabd6d37-59aa-4c63-b2eb-fac8a94300de.png)

**Comment by Y-Kelly** [comment]
@SmithingJon Yes, I believe this issue was fixed last week.  Are you still reproducing?  If you are still having issues, please share feedback through the browser.  

- Either via this shortcut on the Microsoft Edge New Tab Page to invoke the Feedback -> Alt+Shift+I 
- Or you can find and click this button at the bottom right of the New Tab Page

![a8db66ec-473d-4943-ba17-be7a8b424849](https://user-images.githubusercontent.com/74324031/215556537-6199d274-8ca1-4694-bf24-5a1204a37246.jpg)

**Comment by Y-Kelly** [comment]
@SmithingJon Yes, that is the issue that should have been fixed last week. If you are still reproducing please provide feedback through the browser. Thanks

**Comment by Y-Kelly** [comment]
@SmithingJon We had additional reports of the issue not being resolved with the original fix.  The team is working on another update.  I can keep you posted.  Thanks!

**Comment by Y-Kelly** [comment]
@SmithingJon The team has said they have deployed another fix and there is no need to update MS Edge for the fixes to take effect.  Please test and see if you are still reproducing today.
