### ISSUE TITLE
Edge Beta ERR_Unable_to_check_revocation due to MicrosoftRootStoreEnabled policy

### ISSUE THREAD

**Issue by Florin-Anghel** [MicrosoftDocs/Edge-Enterprise#499]
In our organization we have Zscaler and Pulse VPN, so there is SSL inspection.
It seems that Edge beta does not allow browsing to most of the urls due to the deprecation of MicrosoftRootStoreEnabled policy.

For us to make use of Edge Beta we have to configure the policy "Determines whether the Microsoft Root Store and built-in certificate verifier will be used to verify server certificates (deprecated)" to Disabled.

I would have expected that we don't have to configure this policy, usually what's default or untouched does not interefere with browsing, especially since the policy is deprecated.

Could you please check? We would like to avoid any potential issues that might arise to Edge extended stable channel release.

**Comment by erik-anderson** [comment]
The new cert verifier tied to the root store is a little more strict in enforcing _MUST_ requirements in [RFC 5280](https://www.rfc-editor.org/rfc/rfc5280.html).

Are the CRLs PEM encoded? If so, they need to be DER encoded instead. ([Section 4.2.1.13](https://www.rfc-editor.org/rfc/rfc5280.html#section-4.2.1.13) says, "When the HTTP or FTP URI scheme is used, the URI MUST point to a single DER encoded CRL..."). See https://crbug.com/1418236 for more details.

If this isn't the case, can you provide a netlog via edge://net-export?

**Comment by erik-anderson** [comment]
A little more background, in case it's helpful.

If you weren't aware of it already, please see the information at https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-cert-verification.

The reason the `MicrosoftRootStoreEnabled` policy is marked deprecated is because it will not be supported starting in Edge 113. If you need time to update your environment, it's reasonable to use the `MicrosoftRootStoreEnabled` policy in Edge 112 (which will be an extended stable release version).

My assumption based on the error code you're seeing is that you're also enabling the `EnableOnlineRevocationChecks` and/or `RequireOnlineRevocationChecksForLocalAnchors` policies in your environment. Those policies will continue to exist after Edge 112 and could be used to temporarily disable the revocation checks if you need even more time to update your certificates to be RFC 5280 compliant.

**Comment by Florin-Anghel** [comment]
Hello @erik-anderson,

Sorry for my late reply.

You are indeed correc. We are now trying to find out what exactly we need to change.

Our specific root CA is using a CRL distribution point: http://ourdomain/crl2/rootca2.crl

This is pointing to our internal webserver where the CRL file is in DER format BUT webserver hosting it, is serving it with the following header: Content-Type: text/plain.

RFC5280 is specifying that the header should be: HTTP server implementations accessed via the URI SHOULD specify the media type application/pkix-crl in the content-type header field of the response.

As we found out this possible misconfiguration we plan to change it to the Content-Type: application/pkix-crl But we also wanted to verify with you if other changes in Edge could cause the „NET::ERR_CERT_UNABLE_TO_CHECK_REVOCATION“ errors.

**Comment by erik-anderson** [comment]
It's hard to reason about what else could be wrong without a netlog (via edge://net-export).

I don't immediately see anything that would trip over it having that Content-Type, though application/pkix-crl would be better. It's unlikely to resolve your issue.

Some other things to look at:
1. The max response body for the CRL is 5MB.
2. The reasons field should be empty.
3. The distribution point must be a fullName.
4. Only `http://` URLs are supported (you look good here).

**Comment by Florin-Anghel** [comment]
Hello @erik-anderson, the net-export contains to much sensitive data, thus we will create a Microsoft premier support case and it will get assigned to the respective product group.

**Comment by erik-anderson** [comment]
Thanks, I agree that would be best. They should end up routing the issue to me if needed.
