### ISSUE TITLE
Issue with resetting Microsoft Edge sync - unable to find reset option in Settings.

### ISSUE THREAD

**Issue by shayd2110** [MicrosoftDocs/Edge-Enterprise#526]
I followed your article on resetting Microsoft Edge data in the cloud but encountered some issues. After signing out of my account, I opened Microsoft Edge on my desktop, went to Settings > Profiles > Sync, but the "Sync" button was disabled, and I couldn't find the option to "Reset sync."

I believe this might be due to a recent update or change in the Edge interface. As a user, it can be frustrating to follow a guide that is no longer accurate or up-to-date.

I would appreciate it if you could update your article to reflect any changes in the Edge interface or provide alternative solutions to the problem. This will help users like me avoid confusion and frustration when trying to follow your guide.

Thank you for your attention to this matter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa2b6bb-c572-6b62-0b2a-5d11cc6c16c2
* Version Independent ID: bbd72cfb-0dd2-dce0-ede7-6887a2992bad
* Content: [Reset Microsoft Edge data in the cloud](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-reset-data-in-cloud)
* Content Source: [edgeenterprise/edge-learnmore-reset-data-in-cloud.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/edge-learnmore-reset-data-in-cloud.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **collw**

**Comment by Y-Kelly** [comment]
@shayd2110 Just to confirm, were you still signed in on the device you were performing the reset on?  

![image](https://user-images.githubusercontent.com/74324031/235508127-ac034c67-fa75-420a-83bc-d10aa7026efb.png)

Reset sync is at the bottom of the edge://settings/profiles/sync page.

![image](https://user-images.githubusercontent.com/74324031/235508424-be84e785-1f42-4f9f-97e9-1c1c1c7e7497.png)

If you are still having an issue, you can reach out to Support for Business (https://developer.microsoft.com/en-us/microsoft-edge/support/) and they can help investigate your specific case.

**Comment by Dreampenguin** [comment]
Hi. Kelly, I implore you to re-examine what shayd2110 submitted, as I believe you misunderstood his issue (which also seems to be my issue) and prematurely marked it as "completed."

I don't frequently use GitHub but have logged back into my account just so that I can reach out to you in an attempt to resolve this.

The problem is that the "Reset Sync" really doesn't appear any more for some users. I have it on my work PC (using a work e-mail) but not on my home PC (using my personal e-mail). There is literally no longer an option called Reset sync for me at home.

A recent update to Edge seems to have automatically forced many logged-in users to be synced without their permission. In the case of my work account, I could then delete the synced data and stop syncing (while remaining logged in) via the "Reset sync" option being discussed here. However, in the case of my home account, the most I can do is turn off individual sliders for the type of data to sync as well as "Re-sync" my data (but this description is worded in a way that makes it seem like it does not delete cloud data). It's possible I'm mistaken, but I'm not sure where exactly I can check the current status of my Edge cloud data to verify whether or not it is presently still saved.

I have spoken extensively with a Microsoft support agent about this sync issue tonight, but it was definitely out of his league; I don't think he even fully understood me. He suggested I reach out to the Feedback Hub, but upon doing that I saw there was no way to actually chat with anyone and get the issue resolved; I'm doubtful that my feedback thrown into the ether there will actually reach the person it needs to reach and be acted upon.

But perhaps you are that person that it needs to reach - or perhaps you know that person?

What I am specifically requesting is for Edge to be promptly updated such that (1) I can delete all data Microsoft Edge has from me on the cloud & (2) I can remain logged into my account while not syncing.

I was hopeful when I checked edge://flags and saw the Experiment "combine sync consent and sign in." I was on Default, so I thought maybe the root of the issue was that the default behavior changed from Disabled to Enabled for me at home. However, even upon changing the flag to "Disabled" and restarting Edge, I still seem to have this combined experience where being signed in means I'm syncing.

Thank you for any help you can provide.
