### ISSUE TITLE
Please don't use US centric date formats. It's very confusing for the rest of the world. Please use the universal format of: YYYY-MM-DD.

### ISSUE THREAD

**Issue by ccsjnw** [MicrosoftDocs/Edge-Enterprise#83]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d1bc306-56a5-f501-b3e0-a661d57b1db4
* Version Independent ID: e4ef685b-8570-be80-9547-9956042b967e
* Content: [Microsoft Edge release schedule](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-release-schedule)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by krystofkrticka** [comment]
I agree, dates for release schedule should be written using ISO 8601 (YYYY-MM-DD)

**Comment by Y-Kelly** [comment]
Clean up of old issues.  I do see the article has changed the date formatting since this feedback was provided.  Closing.  

If you would like to report another Microsoft Edge Enterprise documentation issue to the team please open a new issue and include relevant information/repro steps in the Comment section.
